<?php
namespace App\Application\DTO;

//Create DTO(Data Transfer Object)for task. 
// Only data we have is the title. 
//Id and date created will be generated by the Domain Entity. 

class TaskDTO{
    public string $title; 
    
    public function __construct (string $title){
        $this->title = $title; 
    }
}
